### ISSUE TITLE
programmatically send bibliography PDF to Zenodo

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/Nisinoon.net#33]
Waiting to meet with @monicamacaulay to turn on Zenodo syncing for her account.

Programmatically send the bibliography PDF to Zenodo.

- [x] Use a gh-pages workflow step to deploy the bibliography PDF to its own branch by itself (`bibliography`).
- [x] Add a release step that uses the bibliography branch to create a release.
- [x] Turn on Zenodo syncing for the repo, then make another test release.

**Comment by monicamacaulay** [comment]
Hi Danny,

I can't figure out how to turn on Zenodo syncing. I have a message from July of 2021 (!) from you telling me how to upload the bibliography, but the file you attached is so old it wouldn't make sense to upload it.

The only thing I could find online was this, but I don't understand what it's telling me to do:
[cid:d4b187bb-6c9e-4a86-b65e-ba8e1b234b07]

So... how do I do this?

Monica
________________________________
From: Daniel W. Hieber ***@***.***>
Sent: Tuesday, December 13, 2022 8:36 PM
To: dwhieb/Nisinoon.net ***@***.***>
Cc: MONICA MACAULAY ***@***.***>; Mention ***@***.***>
Subject: [dwhieb/Nisinoon.net] programmatically send bibliography PDF to Zenodo (Issue #33)


Waiting to meet with @monicamacaulay<https://github.com/monicamacaulay> to turn on Zenodo syncing for her account.

Programmatically send the bibliography PDF to Zenodo.

  *    Use a gh-pages workflow step to deploy the bibliography PDF to its own branch by itself (bibliography).
  *    Add a release step that uses the bibliography branch to create a release.
  *    Turn on Zenodo syncing for the repo, then make another test release.

**Comment by dwhieb** [comment]
@monicamacaulay I hadn't sent instructions for Zenodo yet, so no worries!

- [ ] Log in to Zenodo.
- [ ] Click the dropdown with your username in the top right, and go to the GitHub section.
- [ ] You should see a list of your GitHub repositories. Turn on the switch next to Nisinoon.net.

That's it! Once it's turned on, one of us can manually initiate a release, which will publish the latest version of the bibliography to Zenodo. Instructions for how to make a release are [here](‼️), but I'll test that myself once you've turned on syncing.

**Comment by monicamacaulay** [comment]
I appear to have no repositories...
[cid:e1b7436c-c251-4e59-a059-dad0b5f002cf]
________________________________

**Comment by dwhieb** [comment]
@monicamacaulay Looks like Zenodo requires you to have admin permissions on the repository. I can't give you admin permissions while this repo is under my personal account, but I can if it's under the DLx account. Give me a bit to transfer this repo to the DLx account and unbreak some problems that'll cause, and then we can try again.

**Comment by dwhieb** [comment]
@monicamacaulay Ok, I've transfered the repository and you have admin permissions now. Give it another try!

**Comment by monicamacaulay** [comment]
Did it. Now I forget what I was supposed to do with it. 🤷‍♀️
________________________________

**Comment by dwhieb** [comment]
After testing this out, it looks like the better solution is to just manually upload the new PDF to Zenodo each time we'd like to update it. (See details in my other email.) Closing this issue.
